class Seed

  def self.start
    seed = Seed.new
    seed.create_programs
    seed.create_years
    seed.create_institutions
  end

  def create_programs
    Program.create(cip2:"1", name:"Agriculture, Agriculture Operations, and Related Sciences")
    Program.create(cip2:"2", name: "Agricultural Sciences")
    Program.create(cip2:"3", name:"Natural Resources and Conservation")
    Program.create(cip2:"4", name: "Architecture and Related Services")
    Program.create(cip2:"5", name:"Area, Ethnic, Cultural, Gender, and Group Studies")
    Program.create(cip2:"9", name:"Communication, Journalism, and Related Programs")
    Program.create(cip2:"10", name:"Communications Technologies/Technicians and Support Services")
    Program.create(cip2:"11", name:"Computer and Information Sciences and Support Services")
    Program.create(cip2:"12", name:"Personal and Culinary Services")
    Program.create(cip2:"13", name:"Education")
    Program.create(cip2:"14", name:"Engineering")
    Program.create(cip2:"15", name:"Engineering Technologies and Engineering-Related Fields")
    Program.create(cip2:"16", name:"Foreign Languages, Literatures, and Linguistics")
    Program.create(cip2:"19", name:"Family and Consumer Sciences/Human Sciences")
    Program.create(cip2:"22", name:"Legal Professions and Studies")
    Program.create(cip2:"23", name:"English Language and Literature/Letters")
    Program.create(cip2:"24", name:"Liberal Arts and Sciences, General Studies and Humanities")
    Program.create(cip2:"25", name:"Library Science")
    Program.create(cip2:"26", name:"Biological and Biomedical Sciences")
    Program.create(cip2:"27", name:"Mathematics and Statistics")
    Program.create(cip2:"28", name:"Military Science, Leadership and Operational Art")
    Program.create(cip2:"29", name:"Military Technologies and Applied Sciences")
    Program.create(cip2:"30", name:"Multi/Interdisciplinary Studies")
    Program.create(cip2:"31", name:"Parks, Recreation, Leisure, and Fitness Studies")
    Program.create(cip2:"32", name:"Basic Skills and Developmental/Remedial Education")
    Program.create(cip2:"33", name:"Citizenship Activities")
    Program.create(cip2:"34", name:"Health-Related Knowledge and Skills")
    Program.create(cip2:"35", name:"Interpersonal and Social Skills")
    Program.create(cip2:"36", name:"Leisure and Recreational Activities")
    Program.create(cip2:"37", name:"Personal Awarness and Self-Improvement")
    Program.create(cip2:"38", name:"Philosophy and Religious Studies")
    Program.create(cip2:"39", name:"Theology and Religious Vocations")
    Program.create(cip2:"40", name:"Physical Sciences")
    Program.create(cip2:"41", name:"Science Technologies/Technicians")
    Program.create(cip2:"42", name:"Psychology")
    Program.create(cip2:"43", name:"Homeland Security, Law Enforcement, Firefighting and related protective services")
    Program.create(cip2:"44", name:"Public Administration and Social Service Professions")
    Program.create(cip2:"45", name:"Social Sciences")
    Program.create(cip2:"46", name:"Construction Trades")
    Program.create(cip2:"47", name:"Mechanic and Repair Technologies/Technicians")
    Program.create(cip2:"48", name:"Precision Production")
    Program.create(cip2:"49", name:"Transportation and Material Moving")
    Program.create(cip2:"50", name:"Visual and Performing Arts")
    Program.create(cip2:"51", name:"Health Professions and Related Programs")
    Program.create(cip2:"52", name:"Business, Management, Marketing, and Relate Support Services")
    Program.create(cip2:"53", name:"High School/Secondary Diplomas and Certificates")
    Program.create(cip2:"54", name:"History")
    Program.create(cip2:"60", name:"Residency Programs")
    Program.create(cip2:"20", name:"Family and Consumer Sciences/Human Sciences")
  end

  def create_years
    Year.create(date_year:"2001")
    Year.create(date_year:"2002")
    Year.create(date_year:"2003")
    Year.create(date_year:"2004")
    Year.create(date_year:"2005")
    Year.create(date_year:"2006")
    Year.create(date_year:"2007")
    Year.create(date_year:"2008")
    Year.create(date_year:"2009")
    Year.create(date_year:"2010")
    Year.create(date_year:"2011")
    Year.create(date_year:"2012")
    Year.create(date_year:"2013")
    Year.create(date_year:"2014")
    Year.create(date_year:"2015")
    Year.create(date_year:"2016")
  end

  def create_institutions
    Institution.create(name:"Aims Community College", city:"Fort Lupton", street:"260 College Ave", state:"CO", zip: "80632", phone_number:"(970) 330-8008", web:"www.aims.edu")
    Institution.create(name:"Front Range Community College", city:"Westminster", street:"3645 W 112th Ave", state:"CO", zip: "80031", phone_number:"(303) 404-5000", web:"www.frontrange.edu")
    Institution.create(name:"University of Colorado Denver", city:"Denver", street:"1250 14th St, Denver", state:"CO", zip:"80217", phone_number:"(303) 315-2500", web:"administration.ucdenver.edu")
    Institution.create(name:"Metropolitan State University of Denver", city:"Denver", street:"890 Auraria Pkwy #410", state:"CO", zip:"80204", phone_number:"(303) 556-3058", web:"www.msudenver.edu")
    Institution.create(name:"Colorado Northwestern Community College", city:"Craig", street:"2801 W 9th St", state:"CO", zip:"81648", phone_number:"(970) 675 2261", web:"www.cncc.edu")
    Institution.create(name:"University of Colorado Colorado Springs", city:"Colorado Springs", street:"1420 Austin Bluffs Pkwy", state:"CO", zip:"80918", phone_number:"(719) 255-3000", web:"www.uccs.edu")
    Institution.create(name:"Western State Colorado University", city:"Gunnison", street:"600 Adams St", state:"CO", zip:"81231", phone_number:"(970) 943-0120", web:"www.western.edu")
    Institution.create(name:"Community College of Aurora", city:"Denver", street:"710 Alton Way", state:"CO", zip:"80011", phone_number:"(303) 360-4700", web:"www.ccaurora.edu")
    Institution.create(name:"CSU-Global Campus", city:"Greenwood Village", street:"7800 E Orchard Rd #200", state:"CO", zip:"80111", phone_number:"(800) 920-6723", web:"csuglobal.edu")
    Institution.create(name:"Colorado State University", city:"Fort Collins", street:"1101 Center Ave Mall", state:"CO", zip:"80523", phone_number:"(970) 491-1101", web:"www.colostate.edu")
    Institution.create(name:"Colorado School of Mines", city:"Golden", street:"1500 Illinois St", state:"CO", zip:"80401", phone_number:"(303) 273-3000", web:"www.mines.edu")
    Institution.create(name:"Arapahoe Community College", city:"Littleton", street:"5900 S Santa Fe Dr", state:"CO", zip:"80160", phone_number:"(303) 797-4222", web:"www.arapahoe.edu")
    Institution.create(name:"Trinidad State Junior College", city:"Trinidad", street:"600 Prospect St", state:"CO", zip:"81082", phone_number:"(719) 846-5011", web:"wwww.trinidadstate.edu")
    Institution.create(name:"Colorado Mesa University", city:"Grand Junction", street:"1100 North Ave", state:"CO", zip:"81501", phone_number:"(970) 248-1498", web:"www.coloradomesa.edu")
    Institution.create(name:"Red Rocks Community College", city:"Lakewood", street:"13300 6th Avenue", state:"CO", zip:"80228", phone_number:"(303) 914-6000", web:"www.rrcc.edu")
    Institution.create(name:"Morgan Community College", city:"Fort Morgan", street:"920 Barlow Rd", state:"CO", zip:"80701", phone_number:"(970) 542-3100", web:"www.morgancc.edu")
    Institution.create(name:"Fort Lewis College", city:"Durango", street:"1000 Rim Dr", state:"CO", zip:"81301", phone_number:"(970) 247-7010", web:"www.fortlewis.com")
    Institution.create(name:"University of Colorado Boulder", city:"Boulder", street:"1669 Euclid Ave", state:"CO", zip:"80309", phone_number:"(303) 492-1411", web:"www.colorado.edu")
    Institution.create(name:"Pikes Peak Community College", city:"Colorado Springs", street:"5675 S Academy Blvd,", state:"CO", zip:"80906", phone_number:"(719) 502-2000", web:"www.ppcc.edu")
    Institution.create(name:"Colorado Mountain College", city:"Glenwood Springs", street:"802 Grand Ave", state:"CO", zip:"81602", phone_number:"(970) 945-8691", web:"www.coloradomn.edu/")
    Institution.create(name:"University of Northern Colorado", city:"Greeley", street:"501 20th St", state:"CO", zip:"80639", phone_number:"(970) 351-1890", web:"www.unco.edu")
    Institution.create(name:"Colorado State University - Pueblo", city:"Pueblo", street:"2200 Bonforte Boulevard", state:"CO", zip:"81001", phone_number:"(719) 549-2100", web:"www.csupueblo.edu")
    Institution.create(name:"Adams State University", city:"Alamosa", street:"208 Edgemont Blvd", state:"CO", zip:"81102", phone_number:"(719) 587-7011", web:"www.adams.edu")
    Institution.create(name:"Pueblo Community College", city:"Pueblo", street:"900 W Orman Ave", state:"CO", zip:"81004", phone_number:"(719) 549-3200", web:"www.pueblocc.edu")
    Institution.create(name:"Community College of Denver", city:"Denver", street:"800 Curtis Street", state:"CO", zip:"80217", phone_number:"(303) 55-2600", web:"www.ccd.edu")
    Institution.create(name:"Northeastern Junior College", city:"Sterling", street:"100 College Ave", state:"CO", zip:"80751", phone_number:"(970) 521-6600", web:"www.njc.edu")
    Institution.create(name:"Otero Junior College", city:"La Junta", street:"1802 Colorado Ave", state:"CO", zip:"81050", phone_number:"(719) 384-6831")
    Institution.create(name:"Lamar Community College", city:"Lamar", street:"2401 S Main St", state:"CO", zip:"81052", phone_number:"(719) 336-2248", web:"www.lamarcc.edu")
  end
end
Seed.start

